/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as _authSignUpSplatRouteImport } from './routes/__auth/sign-up.$'
=======
>>>>>>> fe8b04e (tf)
import { Route as _authSignInSplatRouteImport } from './routes/__auth/sign-in.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const _authSignUpSplatRoute = _authSignUpSplatRouteImport.update({
  id: '/__auth/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> fe8b04e (tf)
const _authSignInSplatRoute = _authSignInSplatRouteImport.update({
  id: '/__auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in/$': typeof _authSignInSplatRoute
<<<<<<< HEAD
  '/sign-up/$': typeof _authSignUpSplatRoute
=======
>>>>>>> fe8b04e (tf)
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in/$': typeof _authSignInSplatRoute
<<<<<<< HEAD
  '/sign-up/$': typeof _authSignUpSplatRoute
=======
>>>>>>> fe8b04e (tf)
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__auth/sign-in/$': typeof _authSignInSplatRoute
<<<<<<< HEAD
  '/__auth/sign-up/$': typeof _authSignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in/$' | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in/$' | '/sign-up/$'
  id: '__root__' | '/' | '/__auth/sign-in/$' | '/__auth/sign-up/$'
=======
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in/$'
  id: '__root__' | '/' | '/__auth/sign-in/$'
>>>>>>> fe8b04e (tf)
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authSignInSplatRoute: typeof _authSignInSplatRoute
<<<<<<< HEAD
  _authSignUpSplatRoute: typeof _authSignUpSplatRoute
=======
>>>>>>> fe8b04e (tf)
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/__auth/sign-up/$': {
      id: '/__auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof _authSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> fe8b04e (tf)
    '/__auth/sign-in/$': {
      id: '/__auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof _authSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authSignInSplatRoute: _authSignInSplatRoute,
<<<<<<< HEAD
  _authSignUpSplatRoute: _authSignUpSplatRoute,
=======
>>>>>>> fe8b04e (tf)
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
